# Generated by Django 4.0.4 on 2022-04-15 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.generic.models
import localflavor.nl.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSNProofFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.')], default='MS', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('preposition', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=20)),
                ('zipcode', localflavor.nl.models.NLZipCodeField(max_length=7)),
                ('street_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(default='NL', max_length=2)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mobile_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('drivers_licenses', models.CharField(max_length=100)),
                ('max_travel_one_way_minutes', models.PositiveSmallIntegerField(default=30)),
                ('has_own_bicycle', models.BooleanField(default=False)),
                ('has_own_car', models.BooleanField(default=False)),
                ('work_experience', models.TextField()),
                ('work_willing_to_consider', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidates.CVFile/bytes/filename/mimetype')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', django_countries.fields.CountryField(max_length=2)),
                ('bsn', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d*$')])),
                ('bsn_proof_file', models.FileField(blank=True, null=True, upload_to='candidates.BSNProofFile/bytes/filename/mimetype')),
                ('marital_status', models.CharField(choices=[('UNMARRIED', 'Unmarried'), ('MARRIED', 'Married'), ('COHABITANT', 'Cohabitant'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('UNKNOWN', 'Unknown')], default='UNMARRIED', max_length=15)),
                ('iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False)),
                ('bic', localflavor.generic.models.BICField(max_length=11)),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_valid_to', models.DateField()),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='candidates.PassportFile/bytes/filename/mimetype')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaCertificateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PassportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('CONVERSATIONAL', 'Conversational'), ('PROFESSIONAL', 'Professional'), ('FLUENT', 'Fluent'), ('NATIVE', 'Native')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('diploma_certificate_file', models.FileField(blank=True, null=True, upload_to='candidates.DiplomaCertificateFile/bytes/filename/mimetype')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
    ]
