# Generated by Django 4.0.4 on 2022-04-25 17:32

import candidates.models
from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_languages_delete_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=django_jsonform.models.fields.JSONField(default=candidates.models.default_languages),
        ),
    ]
