# Generated by Django 4.0.4 on 2022-04-25 18:54

import candidates.models
from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='diplomas_certificates',
            field=models.TextField(blank=True, null=True, verbose_name='Diplomas and certificates'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='drivers_licenses',
            field=django_jsonform.models.fields.JSONField(default=dict, verbose_name='Drivers Licenses'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=django_jsonform.models.fields.JSONField(default=candidates.models.default_languages, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Work experience'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_willing_to_consider',
            field=models.TextField(blank=True, null=True, verbose_name='Work willing to consider'),
        ),
    ]
