# Generated by Django 4.0.4 on 2022-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='drivers_licenses',
            field=models.CharField(default='', max_length=200, verbose_name='Drivers Licenses'),
        ),
    ]
