# Generated by Django 4.0.4 on 2022-04-26 14:38

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import localflavor.generic.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_drivers_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Internal comments'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='internal_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bic',
            field=localflavor.generic.models.BICField(blank=True, max_length=11, null=True, verbose_name='SWIFT'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bsn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d*$')], verbose_name='BSN'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bsn_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='BSN proof'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country_of_birth',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country of birth'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='has_own_bicycle',
            field=models.BooleanField(default=False, verbose_name='Own bicycle'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='has_own_car',
            field=models.BooleanField(default=False, verbose_name='Own car'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='iban',
            field=localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, null=True, use_nordea_extensions=False, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('UNMARRIED', 'Unmarried'), ('MARRIED', 'Married'), ('COHABITANT', 'Cohabitant'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('UNKNOWN', 'Unknown')], default='UNMARRIED', max_length=15, null=True, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='max_travel_one_way_minutes',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Maximum travel time to work (in minutes)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Passport scan'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport number'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='passport_valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Passport valid to'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='place_of_birth',
            field=models.CharField(max_length=100, verbose_name='Place of birth'),
        ),
    ]
