# Generated by Django 4.0.4 on 2022-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_comments_candidate_internal_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='work_time_restrictions',
            field=models.TextField(blank=True, null=True, verbose_name='Work time restrictions'),
        ),
    ]
