# Generated by Django 4.0.4 on 2022-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_candidate_created_candidate_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='mobile_phone_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='preposition',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name_cyrillic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name (cyrillic)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='original_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Patronymic'),
        ),
    ]
